### ISSUE TITLE
Help an idiot?

### ISSUE THREAD

**Issue by clarklab** [mgkprod/magenta-machine#1]
Hey! I realize this repo is a few years old, but it's PERFECT for a little game I'm setting up. Can you give me some tips on how to get it running?

- I tried the usual "npm install" etc, locally, and couldn't figure it out
- I tried deploying to Netlify, and the build works, but then still getting "Not Found" on the main URL

Any ideas? Thanks in advance!

**Comment by rubuano** [comment]
Hello @clarklab, at the time the project was made, it was installed using yarn and used Webpack to build the app.

I will be doing an update in a few days to use the latest versions and add information to the readme.

Glad that my project is helpful to you anyways!

I'll leave the issue open and will close once the update is done :)

**Comment by clarklab** [comment]
Hey thanks! I got it building in the meantime, it turns out it wasn't working with my newer version of node. I swapped to Node 16 and everything built fine!

I'll keep an eye out for any updates.

PS: I'm using it to make a soundboard for the party game Werewolf (howls, growls, night, morning, etc)
